SITE_TITLE = "Boilerplate app"
SITE_SUBTITLE = "A site about nothing..."
SECURITY_PASSWORD_HASH = 'bcrypt'
SECURITY_URL_PREFIX = '/auth'
SECURITY_CHANGEABLE = True
SECURITY_SECURITY_SEND_PASSWORD_CHANGE_EMAIL = False
FRONTEND_ITEMS_PER_PAGE = 3
BACKEND_ITEMS_PER_PAGE = 20
