SITE_TITLE = "Boilerplate app"
DEBUG_TB_INTERCEPT_REDIRECTS = False
SECURITY_PASSWORD_HASH = 'bcrypt'
SECURITY_URL_PREFIX = '/auth'
SECURITY_CHANGEABLE = True
SECURITY_SECURITY_SEND_PASSWORD_CHANGE_EMAIL = False
